# Generated by Django 3.2.7 on 2021-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceusers',
            name='AccountName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceusers',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceusers',
            name='Type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
