# Generated by Django 3.2.7 on 2021-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForceUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.CharField(max_length=300)),
                ('Type', models.CharField(max_length=300)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
